# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8hdkLdkDIa2TLWA21FtReFnYzlSOXB4
"""

# 1. Upload your Lamborghini excel file
from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

# 2. Read Excel sheet and clean trailing spaces
file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name, sheet_name=0)
df['Metric'] = df['Metric'].astype(str).str.strip()

years = ['FY 2022', 'FY 2023', 'FY 2024', 'FY 2025']

# 3. Generate Chart 1: Revenue, Operating Profit & Cars Delivered
revenue = df[df['Metric'] == 'Revenuve (millions)'][years].values[0]
op_profit = df[df['Metric'] == 'Operating profit (millions)'][years].values[0]
cars_delivered = df[df['Metric'] == 'Cars delivered'][years].values[0]

fig, ax1 = plt.subplots(figsize=(8, 4.5), dpi=300)
x = range(len(years))
width = 0.35

ax1.bar([p - width/2 for p in x], revenue, width=width, label='Revenue (€M)', color='#1f77b4')
ax1.bar([p + width/2 for p in x], op_profit, width=width, label='Operating Profit (€M)', color='#d62728')
ax1.set_ylabel('Amount (€ Millions)', fontsize=11, fontweight='bold')
ax1.set_xticks(x)
ax1.set_xticklabels(years)
ax1.set_ylim(0, 3800)

ax2 = ax1.twinx()
ax2.plot(years, cars_delivered, color='#2ca02c', marker='o', linewidth=2.5, label='Cars Delivered')
ax2.set_ylabel('Cars Delivered (Units)', color='#2ca02c', fontsize=11, fontweight='bold')
ax2.set_ylim(8000, 12000)

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left')

plt.title('Lamborghini: Revenue, Operating Profit & Deliveries (2022–2025)', fontsize=12, fontweight='bold', pad=15)
fig.tight_layout()
plt.savefig('lamborghini_performance.png')
plt.show()

# 4. Generate Chart 2: Unit Economics & Operating Margin
rev_per_car = df[df['Metric'] == 'Revenue per car (thousand)'][years].values[0]
op_profit_per_car = df[df['Metric'] == 'Operating profit per Car (thousand)'][years].values[0]
op_margin = df[df['Metric'] == 'Operating margin'][years].values[0] * 100

fig, ax1 = plt.subplots(figsize=(8, 4.5), dpi=300)

ax1.plot(years, rev_per_car, marker='s', linewidth=2.5, label='Revenue per Car (€k)', color='#1f77b4')
ax1.plot(years, op_profit_per_car, marker='^', linewidth=2.5, label='Operating Profit per Car (€k)', color='#ff7f0e')
ax1.set_ylabel('€ Thousands per Car', fontsize=11, fontweight='bold')
ax1.set_ylim(0, 350)
ax1.grid(True, linestyle='--', alpha=0.5)

ax2 = ax1.twinx()
ax2.plot(years, op_margin, marker='o', linewidth=2.5, color='#2ca02c', linestyle='--', label='Operating Margin %')
ax2.set_ylabel('Operating Margin (%)', color='#2ca02c', fontsize=11, fontweight='bold')
ax2.set_ylim(15, 32)

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2, loc='lower right')

plt.title('Lamborghini: Unit Economics & Operating Margin Trend (2022–2025)', fontsize=12, fontweight='bold', pad=15)
fig.tight_layout()
plt.savefig('lamborghini_margin_trends.png')
plt.show()

# 5. Automatically download saved PNG images
files.download('lamborghini_performance.png')
files.download('lamborghini_margin_trends.png')